#!/bin/sh
# See README.md in build directory

# -----------------------------------------------------------------------------
# CONSTANTS AND DEFAULTS
# -----------------------------------------------------------------------------

FIRSTRUN_MARKER='/docker-setup_done-marker'
DEFAULT_ACTION='help' # scripts may be called with no args, manually


# -----------------------------------------------------------------------------
# SETUP 
# -----------------------------------------------------------------------------

set -eu 

# put everything here what needs to be done at first run, use env vars
setup() {
    /bin/true # dummy line, remove it
}

if ! test -d "$FIRSTRUN_MARKER"; then
    touch "$FIRSTRUN_MARKER"
    setup
fi

# -----------------------------------------------------------------------------
# START OPTIONS
# -----------------------------------------------------------------------------

case "${1:-$DEFAULT_ACTION}" in
    start) 
        # start daemon in foreground (regular docker start)
        exec dnsmasq --keep-in-foreground --no-daemon
    ;;
    reload) 
        # re-read config file(s) but do not break continueous operation
        echo "Config file reload is not supported by dnsmasq"
    ;;
    test) 
        # test config file correctness without interupting daemon operation 
        exec dnsmasq --test
    ;;
    version) 
        # print version information
        exec dnsmasq --version
    ;;
    login) 
        # execute shell login
        exec /bin/bash -l
    ;;
    help) 
        # print help about container operation (and this option stuff)
        exec cat '/docker-readme.md'
    ;;
    *)  
        # run any shell command specified at command line
        exec "${@:-}"
    ;;
esac
